---
title: "Instructions"
author: "Bryony"
date: "February 16, 2017"
output: html_document
---


# Reproducible GLM example with Steph Locke


## Setting up

install packrat package (will require Rtools installation too)
restart R Studio

Option 1:
Create project in R Studio
Enable packrat
Install caret package
Create new respository on github
Commit changges
Use github bash to push changes: 
 - push an existing repo

Option 2:
Create empty repo on github
Create R project by cloning github repo
enable packrat
install caret
commit changes
pus changes

Disaster workaround (here's one I made earlier):
New RStudio instance
New project from source control
Fork example from stephlocke/ReproducibleGLM-step1
Clone to new RStudio project


## Getting the data
get_data.R script file:

__start of file__

### ---- makedb
library(DBI)
library(RSQLite)
titanicdb<-dbConnect(SQLite(),dbname="data-raw/titanic.sqlite")

### ---- writeTitanic
library(PASWR)
dbWriteTable(titanicdb, "titanic", titanic3, overwrite=TRUE)

__end of file__



